Pagina\SpccBundle\Entity\Comments:
    type: entity
    table: comments
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nameComment:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: name_comment
        emailComment:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: email_comment
        comments:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        status:
            type: boolean
            nullable: true
            options:
                default: true
        fechaReg:
            type: date
            nullable: true
            column: fecha_reg
    lifecycleCallbacks: {  }
