Pagina\SpccBundle\Entity\Configuration:
    type: entity
    table: configuration
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        config:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        registerDate:
            type: date
            nullable: true
            column: register_date
        userId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_id
        state:
            type: boolean
            nullable: true
            options:
                default: true
    lifecycleCallbacks: {  }
