Pagina\SpccBundle\Entity\Gallery:
    type: entity
    table: gallery
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        imageGallery:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: image_gallery
        registerDate:
            type: date
            nullable: true
            options:
                default: now()
            column: register_date
        userId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_id
        ocupacionId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ocupacion_id
        state:
            type: boolean
            nullable: true
            options:
                default: true
        typeId:
            type: smallint
            nullable: true
            options:
                unsigned: false
                default: '1'
            column: type_id
    lifecycleCallbacks: {  }
